### ISSUE TITLE
Changing accordion group programaticaly

### ISSUE THREAD

**Issue by Agamennon** [pineconellc/angular-foundation#103]
Is there a way to change what group is open on a accordion programaticaly?
i have tried to bind to is-open attribute but it does not respond (this needs to be a two way binding) i guess...

thanks for this, incredible work!

**Comment by teo89** [comment]
Hey  @Agamennon i have the same issue with you. How exactly did you bind your $scope.isOpen val with $parent.var? 
thanks in advance
