### ISSUE TITLE
Bring the Menu Icon back in toggle-top-bar (in plunker example)

### ISSUE THREAD

**Issue by charleslouis** [pineconellc/angular-foundation#107]
Hey there !

First of all, many thanks for such a great resource !
I've been using foundation with wordpress (https://github.com/kartonnade/basement) for some time but I'm pretty new to angular and I'm glad I can use angular-foundation !

I just write to let you know about a little ``<span>`` missing around ``<span>Menu</span>`` in the website in the [top-bar plunker example](http://pineconellc.github.io/angular-foundation/#/topbar). Hence the 3 " _ " do not show.

``<li toggle-top-bar class="menu-icon"><a href="#">Menu</a></li>``
![image](https://cloud.githubusercontent.com/assets/2117081/4174341/bb6c0d00-3587-11e4-899e-533bd18f2673.png)

``<li toggle-top-bar class="menu-icon"><a href="#"><span>Menu</span></a></li>``
![image](https://cloud.githubusercontent.com/assets/2117081/4174343/d9d6a23c-3587-11e4-9e1c-25d591cfbb2b.png)

**Comment by jbrowning** [comment]
Not sure how/when this was fixed but the :hamburger: icon now appears with the existing markup: http://plnkr.co/edit/m50CF3nd6pOE9eNt1Crn?p=preview
