### ISSUE TITLE
typeahead keyboard navigation visual feedback

### ISSUE THREAD

**Issue by cbosco** [pineconellc/angular-foundation#115]
1. typeahead borrows its styling from Foundation `f-dropdown`
2. typeahead only shows visual feedback on `:hover` and `:focus` based on [foundation 5's CSS rules](https://github.com/zurb/bower-foundation/blob/master/scss/foundation/components/_dropdown.scss#L208-L209)

This may be more rightly an issue for foundation 5, but I think the fix could go here, since `f-dropdown` is extended to use keyboard navigation only here, as far as I can tell.

Example is available on the angular-foundation demo: http://pineconellc.github.io/angular-foundation/#/typeahead (just use the keyboard to select items)

My fix was to add a line to my own app's SCSS file:

```
// for type-ahead keyboard navigation (default is just :focus, :hover)
.f-dropdown li.active { background: $f-dropdown-list-hover-bg; }
```

Since the state is trackable by the `active` class.

**Comment by bastianh** [comment]
Yes, please add this to the docs...
