### ISSUE TITLE
Width of the Typeahead Control

### ISSUE THREAD

**Issue by rince1013** [pineconellc/angular-foundation#145]
Question, how do I control the width of the typeahead control? 
Currently super long strings will wrap and go past the boundaries of the dropdown part of the control

![screenshot 2014-11-06 16 17 57](https://cloud.githubusercontent.com/assets/3579529/4944982/eccc9530-6602-11e4-9587-3a00709a0240.png)

**Comment by legendarydrew** [comment]
More helpfully: Foundation's CSS sets `.f-dropdown` to have a max-width of 200px.

It would be useful to have the dropdown match the width of the input, or even to use Foundation's additional classes on the dropdown (tiny, small, medium, large).
http://foundation.zurb.com/docs/components/dropdown.html
