### ISSUE TITLE
`ControllerAs` option for `$modal`

### ISSUE THREAD

**Issue by tamakisquare** [pineconellc/angular-foundation#175]
it's great that `$modal` already has support for the controller-as syntax, but the use of it is limited to registered controllers. It's not uncommon to see developers use anonymous function or local function as modal controller, without registering the function as an angular controller beforehand. This is where `ControllerAs` option comes in. Indeed, this is how it's done in many other popular modules like **angular-route**, **ui-bootstrap**, just to name a few.

**Comment by blcook223** [comment]
I have found myself wanting this feature, too. I'd love to see PR #176 implemented.

**Comment by jbrowning** [comment]
#176 has been merged.
