### ISSUE TITLE
Close button not working

### ISSUE THREAD

**Issue by blanchma** [pineconellc/angular-foundation#184]
<alert id="errors" type="danger" class="radius" close >
      <p ng-repeat="error in errors" class="error_msg">{{error}}</p>
    </alert>

The close button is rendered but when I click it, nothing happen.

**Comment by fulup-bzh** [comment]
I have the same issue. I check the source code and I fail to understand why. The alert template generate a  ng-click='close()' that should close the alert box as soon as we click on it, doesn't it ?

**Comment by jbrowning** [comment]
The alert directive declares the following scope:

```javascript
scope: {
  type: '=',
  close: '&'
}
```

Thus, when the close button is clicked, the expression within the close attribute is evaluated. It is up to you to actually remove the alert element from the DOM (this is usually accomplished via a `ng-if`, `ng-show`, or `ng-hide`).

The documentation is lacking here. :no_mouth:

**Comment by fulup-bzh** [comment]
Thank you for this quick response. It effectively works. Oviously the chosen var name has to be unique to each alert box, or in one click you close all of them.
```
 <alert data-ng-hide="closeAlert1" close="closeAlert1=true"> dfsdfsdf</alert>
 <alert data-ng-hide="closeAlert2" close="closeAlert2=true"> 1234</alert>
```

**Comment by blanchma** [comment]
Many thanks!
