### ISSUE TITLE
Navigating away from a page with an open tour, do not close the tour

### ISSUE THREAD

**Issue by vikasgarghb** [pineconellc/angular-foundation#187]
Hi, I have a scenario where I have a page with the tour functionality. I have the tour open on that page and if I navigate away from that page, the tour do not close but still shows up on the same spot where it was on the previous page.

I want the tour to stop, if the user has navigated away from the page.

**Comment by circlingthesun** [comment]
Stange, if the elements which the tooltips are attached to are no longer on screen, they should not show. You should probably attach a function to the ```$locationChangeSuccess``` event that closes the tour.

**Comment by vikasgarghb** [comment]
That's what I did finally to close it. Thanks for the response.

**Comment by jbrowning** [comment]
The automatic closing of tooltips only occurs when the tooltip is appended to the body, which is not the default behavior. Just fixed the tour so it closes when the location changes.
