### ISSUE TITLE
mobile menu icon missing

### ISSUE THREAD

**Issue by percy3d** [pineconellc/angular-foundation#190]
Hi there,

The menu icon is missing. Running version 0.5.1. Not sure why but thought I'd let you know. I see you have it in your example page can't figure what's missing

    <div>
      <top-bar>
       <ul class="title-area">
         <li class="name">
           <h1><a href="#/">my site</a></h1>
          </li>
         <li toggle-top-bar class="menu-icon" menu-icon><a href=''>||||</a></li>
       </ul>

        <top-bar-section>
          
          <ul class="left">
            <li><a href="#/">Home</a></li>
            <li><a href="#/contact/">Contact</a></li>
            <li><a href="#/faq">FAQ</a></li>
            <li><a href="#/about">About</a></li>
          </ul>
        </top-bar-section>
      </top-bar>
    </div>

**Comment by arjendeblok** [comment]
The problem is that you need an extra span within the achor. 

```javascript
<li toggle-top-bar class="menu-icon" menu-icon><a href=''><span>||||</span></a></li>
```

**Comment by percy3d** [comment]
Thanks. I eventually figured that out.

<dan />
