### ISSUE TITLE
<progressbar> animation isn't working

### ISSUE THREAD

**Issue by NirHemed** [pineconellc/angular-foundation#191]
See this plunker : http://plnkr.co/edit/2sZ17RAEKmfjRe5JMHcZ?p=preview
(It is a minor modification of the formal example from the demo page)

**Comment by jbrowning** [comment]
Foundation's CSS does not include a `transition` for the progress bar. I've updated the docs with a better explanation and example here: https://pineconellc.github.io/angular-foundation/#progressbar.
