### ISSUE TITLE
All plunker not working

### ISSUE THREAD

**Issue by zerouno62** [pineconellc/angular-foundation#192]
I have noticed that all plunker examples do not work. 
In the JS console you will find the following message:

 URL visited /edit/
angular.js:1747 Uncaught Error: [$injector:nomod] Module 'foundationDemoApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.3/$injector/nomod?p0=foundationDemoApp
angular.js:11413 Error: [ng:areq] Argument 'AccordionDemoCtrl' is not a function, got undefined
http://errors.angularjs.org/1.3.3/ng/areq?p0=AccordionDemoCtrl&p1=not%20a%20function%2C%20got%20undefined
    at angular.js:63
    at assertArg (angular.js:1560)
    at assertArgFn (angular.js:1570)
    at angular.js:8347
    at angular.js:7517
    at forEach (angular.js:330)
    at nodeLinkFn (angular.js:7504)
    at compositeLinkFn (angular.js:7003)
    at compositeLinkFn (angular.js:7006)
    at compositeLinkFn (angular.js:7006)

Changing the code in the example.js file
from
    angular.module('plunker', ['mm.foundation']);
    angular.module('foundationDemoApp').controller('AccordionDemoCtrl', function($scope) {

to
    var app = angular.module('plunker', ['mm.foundation']);
    app.controller('AccordionDemoCtrl', function($scope) {

makes it work.

**Comment by jbrowning** [comment]
Thanks for reporting this. Just pushed a fix. Let us know if you're still seeing issues.
