### ISSUE TITLE
Bower install failing. Not sure if Github issue or this repo.

### ISSUE THREAD

**Issue by tskaggs** [pineconellc/angular-foundation#194]
Tried to bower install.
----
bower install angular-foundation --save 
bower not-cached    git://github.com/pineconellc/angular-foundation-bower.git#*
bower resolve       git://github.com/pineconellc/angular-foundation-bower.git#*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/pineconellc/angular-foundation-bower.git", exit code of #128

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=Operation timed out

**Comment by tskaggs** [comment]
Looks to be a port issue on my end maybe.
https://github.com/eschnou/ardrone-webflight/issues/49

**Comment by tskaggs** [comment]
Using `git config --global url."https://".insteadOf git://` fixes it without waiting for sysadmin to update the firewall.

**Comment by jbrowning** [comment]
Sounds good.

**Comment by rohitsinghsengar** [comment]
Works for me!
