### ISSUE TITLE
Just pushed on git a Date Picker for Angular/Foundation

### ISSUE THREAD

**Issue by fulup-bzh** [pineconellc/angular-foundation#198]
While it took me some time to accept that Foundation may not have a DatePicker, I finally had to write one. Hopefully it may help other angular-foundation users. 

Code: https://github.com/fulup-bzh/DatePicker
Demo: http://breizhme.net/datepicker/demo

Syntax:
```
<date-picker
   id="picker-1" class="my-date-picker"
   format="(EEE) dd-MMM-yyyy" placeholder="Basic Date Selection" today="Today Not Tomorrow"
  ng-model="pickdate1" callback="datePickerCB">
</date-picker>
```

**Comment by jbrowning** [comment]
Thanks for the info @fulup-bzh. Please open a Pull Request if you'd like to contribute to the project.
