### ISSUE TITLE
Equalizer

### ISSUE THREAD

**Issue by aaronklaser** [pineconellc/angular-foundation#200]
Not really an issue, just no time to properly contribute. I wrote an equalizer directive and wanted to share it. 

 (function () {
    'use strict';

    angular.module('directive.equalizer', []);

    angular.module('directive.equalizer').directive('equalizer', equalizerDirective);

    equalizerDirective.$inject = [];

    function equalizerDirective() {
        return {
            restrict: 'A',
            link: link
        }
    }

    // equalizer on container ==> equalizer-watch on all children inside equalizer. Height will match the tallest child.
    var link = function(scope, element, attrs){
        var items = element.find('[equalizer-watch]');
        var biggest = _.max(items, function(e){ return e.clientHeight; });
        element.find('[equalizer-watch]').css('height', biggest.clientHeight);
    }

})();

**Comment by jbrowning** [comment]
Thanks for the info @aaronklaser. Please open a Pull Request if you'd like to contribute this to the project.
