### ISSUE TITLE
Pushed on git a port of RangeSlider for Angular

### ISSUE THREAD

**Issue by fulup-bzh** [pineconellc/angular-foundation#201]
Just commited a port of Foundation Range Slider port for Angular.

 - Source: https://github.com/fulup-bzh/RangeSlider
 - Demo:  http://breizhme.net/rangeslider/demo

While I used standard Foundation CSS, I unuckly had to rewrite almost 100% of JS part to comply with Angular way of doing things. The good news is that Angular makes possible to add few extra fonctionnalities on top of standard Foundation range-sliders.
 - min/max values but also start/stop to dynamically reduce the scope of a slider [ex: checkin/checkout]
 - by-step increment, but also steping by decimals [ex: by minutes for a timer]
 - external formatters to move from internal to external view [nice for time, date, price, etc ...] 
 - application validation callback when a slider blur.
 - two handles slider for anges (price, time, etc)

Still very early days of this new Angular/Foundation script. It probably needs some polishing but hopefully foundamentals are in place.

**Comment by jbrowning** [comment]
Thanks for the info @fulup-bzh. Please open a Pull Request if you'd like to contribute this to the project.

**Comment by fulup-bzh** [comment]
I'm currently busy working on many projects and do not have enough free to add a new project on my plate. But as soon as I have more time I would be please to propose a Pull Request. I just to check how big would be the effort to push it. I also made a datepicker componant that could be usefull.
