### ISSUE TITLE
How to load controller file of modal directive dynamically

### ISSUE THREAD

**Issue by yonus** [pineconellc/angular-foundation#202]
In web application there are a lot of modal template (angular foundation modal). When the modal is opened, we must give controller . because of a lot of modals , we writing  controllers of modal in js file.
if controller js of each modal  is loaded  seperately as js file ,this is not efficient for me.  so  , I want to load controller of the modal , when the modal is opened.
It is like :

var modalInstance = $modal.open({ templateUrl: 'myModalContent.html', 
                                 controller: 'modal-controller.js' })
can it be done? if so, how can I do that this,

thank your helps

**Comment by jbrowning** [comment]
The modal directive is not concerned with the loading of JS files. That should be handled by whatever method you use to compile and concatenate your app's JS files. The controller that you specify in the controller parameter is Angular's name for the controller, not the filename of the controller.
