### ISSUE TITLE
Can't put typeahead above other grid-block

### ISSUE THREAD

**Issue by pidupuis** [pineconellc/angular-foundation#211]
See the following [plunker](http://plnkr.co/edit/PZRCmbyCxwMU9aAgtybX?p=preview) (better with smaller screen).

I'm using [foundation-apps](http://foundation.zurb.com/apps/docs/#!/grid) with grid-blocks generated by `ng-repeat`. The inputs are using [angular-foundation](http://pineconellc.github.io/angular-foundation/) typeahead. When you type an 'a' in one of the input, the dropdown will appear strictly within its grid-block. Consequently I obtain a scroll bar while I would like to see the dropdown above everything else...

A z-index does not seem to change anything.

**Comment by jbrowning** [comment]
Thanks @pidupuis. angular-foundation is meant to work with what is now called Foundation for Sites. Foundation for Apps and its grid system is a completely different beast and is very likely incompatible with angular-foundation's components. Sorry for the confusion.

**Comment by pidupuis** [comment]
Thanks for your response. Yes that's confusing ^^'

But anyway the Foundation for Apps team found a solution to my problem, see this [issue](https://github.com/zurb/foundation/issues/6464).
