### ISSUE TITLE
Adding typeahead-focus-first=false option

### ISSUE THREAD

**Issue by robbse** [pineconellc/angular-foundation#212]
Hi folks, is it possible to add the typeahead-focus-first=false option like it is descript here: https://github.com/angular-ui/bootstrap/pull/2916

Thanks in advance!

**Comment by japel** [comment]
that would be awesome!

+1

**Comment by jbrowning** [comment]
No that feature does not exist yet. It was added to angular-bootstrap after we forked. Feel free to submit a Pull Request if you'd like to add this feature. :wink:
