### ISSUE TITLE
Typeahead not highlighted when using arrows

### ISSUE THREAD

**Issue by pidupuis** [pineconellc/angular-foundation#215]
You can see it in the [demo](http://pineconellc.github.io/angular-foundation/#/typeahead) by typing `"al"` in the input, then by pressing two times the arrow down and finally by pressing enter. You will see `"California"` appear in the input so the use of the arrow is working but there is no highlight inside the dropdown showing that this is working.

**Comment by jbrowning** [comment]
That is because Foundation's CSS does not have a style for dropdown items with the active class, only on hover. You'll need to style this yourself in CSS.
