### ISSUE TITLE
Typeahead - Event propagation on-select (mouse vs keyboard)

### ISSUE THREAD

**Issue by soyuka** [pineconellc/angular-foundation#217]
Hi, 
NB: I was able to reproduce this on Firefox only.

On the typeahead the click event is well propagated but on `keypress` isn't. I've discovered this while using the typeahead to open a link, for example: 

```
  $scope.select = function(selected) {
    var filename = window.location.pathname.split('/')
    filename = filename[filename.length - 1]

    var link = window.location.href.replace(filename, 'ft/'+selected.path+'.pdf')
    window.open(link)
  }
```

HTML:
```
typeahead_on_select: 'select(selected)'
```

If you click, `window.open` will work just fine. If you send `enter`, you'll get a popup warning (FF). I think that this is because:

> Popup blockers will typically only allow window.open if used during the processing of a user event (like a click).

[source](http://stackoverflow.com/questions/9514698/bypass-popup-blocker-on-window-open-when-jquery-event-preventdefault-is-set)

-----------------

Is there a way to get back the `$event` object in my `typeahead_on_select`? `typeahead_on_select=fn($event, current)` doesn't seem to work.

**Comment by jbrowning** [comment]
Hi @soyuka. No, the event is not passed to the callback function. As you can see [here](https://github.com/pineconellc/angular-foundation/blob/master/src/typeahead/typeahead.js#L214-L218), the callback is given `$item`, `$model`, and `$label`.

**Comment by soyuka** [comment]
Yes I've seen this and tried to tweak a bit.

I'm not getting those elements back in my `callback`.  Actually with `typeahead_on_select='select(selected)'` I'm getting the current `selected` item as specified. There are no docs about how this `typeahead_on_select` should be implemented to get `($item, $model, $label)`, could you point me in the right direction? Also adding `$event` would be nice.

----

About my other issue, the `click` event is well propagated - popup security would not be activated because it's a detected user action. But with the keyboard, I'm having this security issue on Firefox. So this might be event-related; firefox does not received the `enter (13)` key as a user action. Hope it's clear enough, this is hard to explain.
