### ISSUE TITLE
backdropClass for $modal

### ISSUE THREAD

**Issue by FaheemAlam** [pineconellc/angular-foundation#239]
it's pretty awesome that almost all the functionalities for foundation reveal are provided by `$modal`. But I ran into a situation where I need to change the css of `backdrop`. I figure it out that **angular ui bootstrap** does support custom class for `backdrop`.

**Comment by FaheemAlam** [comment]
is there any alternative way to do it ?

**Comment by jbrowning** [comment]
Hello. Currently there's no way to add a custom class to the modal backdrop. To do this, you'll either need to customize the JS that powers the modal backdrop or use your own templates.
