### ISSUE TITLE
typeahed problem in 1.4.1 [filter:notarray] Expected array but received: {} (in 

### ISSUE THREAD

**Issue by DinisCruz** [pineconellc/angular-foundation#243]
using the http://pineconellc.github.io/angular-foundation/#/typeahead example on angular 1.4.1 throws this error:

![image](https://cloud.githubusercontent.com/assets/656739/8512386/f65c3748-2337-11e5-97c3-1bac63f69628.png)

With angular 1.3.3 it works fine:

![image](https://cloud.githubusercontent.com/assets/656739/8512401/4f495034-2338-11e5-8acb-141f7d912c1b.png)

I think the problem is at

```html
<input type="text" ng-model="asyncSelected" placeholder="Locations loaded via $http" typeahead="address for address in getLocation($viewValue) | filter:$viewValue" typeahead-loading="loadingLocations" class="form-control">
    <i ng-show="loadingLocations" class="glyphicon glyphicon-refresh"></i>
```

**Comment by DinisCruz** [comment]
note: the issue seems to be with the ``` filter:$viewValue```

**Comment by mvarshavsky** [comment]
Appear to be running into the same problem in 1.4.2

**Comment by jbrowning** [comment]
Thanks for the report. As noted in the docs, this library is compatible with Angular 1.2 and 1.3. We haven't upgraded to 1.4 yet as none of our internal apps have been upgraded yet. Any assistance from the community to get us on 1.4 would be appreciated.

**Comment by jbrowning** [comment]
This is due to the filter in the example's `typeahead` declaration and https://github.com/angular/angular.js/commit/cea8e75144e6910b806b63a6ec2a6d118316fddd.

```
"address for address in getLocation($viewValue) | filter:$viewValue"
```

Prior to 1.4, filters which were supplied with a non-array would silently return an empty array. Now they raise an error.

**Comment by gregarega1993** [comment]
Any workaround for this?
