### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by randallagordon** [pineconellc/angular-foundation#249]
Curious if there are plans in place to publish on npm now that Angular can be used directly with Browserify? I see someone else published one (http://npm.im/angular-mm-foundation); but without the dist files coming along for the ride, using it currently requires a post-install script.

**Comment by jbrowning** [comment]
Done! https://www.npmjs.com/package/angular-foundation

**Comment by randallagordon** [comment]
Brilliant, thanks so much! :)

**Comment by OndeVai** [comment]
Hi, it looks like this package is different than https://www.npmjs.com/package/angular-mm-foundation. That makes things confusing for most developers :) Could you just publish the package with both the source javascript and the "compiled" javascript? And maybe do it whenever a minor version is bumped automatically like with bower?
