### ISSUE TITLE
Template for accordion-group forces display: block

### ISSUE THREAD

**Issue by ajmair01** [pineconellc/angular-foundation#262]
In the accordion-group template, you have `ng-style="isOpen ? {display: 'block'} : {}"` on the `.content` div.

This causes some styling issues when you want to apply an `inline-block` display to content inside the accordion-group.

Could you change it to `ng-style="isOpen ? {} : {display: 'none'}`? That way, the content div will inherit the display style when it is open, rather than forcing it to `display: 'block'`. I'm sure you would also have to refactor some other components of the accordion to make this work as well.

**Comment by jbrowning** [comment]
This was already fixed by #228 and is included in the just-released v0.7.0.
