### ISSUE TITLE
Directive that will combine search and select

### ISSUE THREAD

**Issue by riley2penna** [pineconellc/angular-foundation#264]
I would like to have an input where I can type to find the item I want, or I can select from the list of items that drops down.

I have seen several directives created for Angular-Bootstrap, but I cannot find anything that I can use with my Angular-Foundation app.  Is this by chance in the works?  If not, has anyone been able to implement this in their Angular-Foundation app?

Thanks

**Comment by jbrowning** [comment]
I think you're looking for Typeahead. Have a look at the demo site at http://pineconellc.github.io/angular-foundation/
