### ISSUE TITLE
Modal animation broken.

### ISSUE THREAD

**Issue by jeremyhewett** [pineconellc/angular-foundation#272]
This issue is related to Issue #203.
The problem is not the delay itself, but rather that the animation that is supposed to happen during that delay is broken. This can be seen on angular-foundation's own plunker: http://plnkr.co/edit/RIsBM1uGbYMwUVTzNtN3?p=preview

The modal does not animate in or out. It shows instantly with no animation, and then closes in two ugly steps with no animation.

**Comment by jbrowning** [comment]
As noted in the animation section of the docs, Foundation 5 supplies animations via Javascript, not CSS. To animate the modal, you'll need to supply your own animations via CSS. You can see the animations we use for the demo site here: https://github.com/pineconellc/angular-foundation/blob/master/misc/demo/assets/demo.css#L323-L345

**Comment by jeremyhewett** [comment]
@jbrowning, I see, thanks for the explanation, makes sense. However, should you not consider providing that CSS with this library? Since templates are already provided I feel like providing the basic CSS to make it "work out of the box" would be great too. And shouldn't be difficult since you already have it.
