### ISSUE TITLE
pagination should allow minimalistic or open-end style

### ISSUE THREAD

**Issue by thomas-koch-comsolit** [pineconellc/angular-foundation#273]
There are different pagination styles that currently doesn't seem to be possible with the pagination directive:
- open-end: show the first-link but not the last-link
- always show page number 1 instead of a a first-link
- show the first-link only when we're not on the first page, same for last-link
- show previous and next links only if they are active

I'm not sure, what would be the best way to expose this options in the directives attributes.

**Comment by jbrowning** [comment]
We've tried to keep our pagination component relatively simple so there are always going to be styles that it can't handle natively. If you need to implement a different style, you could always create your own templates.
