### ISSUE TITLE
Issue with topbar and typeahead

### ISSUE THREAD

**Issue by aejt** [pineconellc/angular-foundation#275]
I'm not completely sure if this is an issue that I should post here, but after many hours of trying to solve it by overwriting CSS I've decided to post it here. I'm sorry if it's just me doing something wrong.

The issue is that if I use a typeahead within a topbar, it ends up looking like this: http://i.imgur.com/ArzwzrE.png

Here's a plunker in which it happens: http://plnkr.co/edit/PsjaLIq4obXHlaPYKZqW

**Comment by jbrowning** [comment]
Sorry this *is* something you'll need to to override with CSS because that's the issue here. Foundation's topbar CSS is particularly aggressive and we don't include any additional CSS in our library.

**Comment by aejt** [comment]
Alright, I'll keep trying then, thanks!
