### ISSUE TITLE
Joyride/Tour modal popup

### ISSUE THREAD

**Issue by vimes1984** [pineconellc/angular-foundation#277]
Whats the syntax to use the tour as a modal popup?

**Comment by vimes1984** [comment]
The modal don't work?

**Comment by jbrowning** [comment]
I'm not sure what you mean or what you're trying to do. We have two separate components here, Modal and a tooltip-based Tour.

**Comment by vimes1984** [comment]
step 3 here: http://foundation.zurb.com/sites/docs/v/5.5.3/components/joyride.html

**Comment by jbrowning** [comment]
Ah, no we don't have support for that. In our Tour component, steps are defined on their target elements so there's really no way to define a tour step without a target element.

**Comment by vimes1984** [comment]
thats what I thought :D

**Comment by vimes1984** [comment]
if I get time I'll patch it and pu tin apull request
