### ISSUE TITLE
window.html and backdrop.html - 404

### ISSUE THREAD

**Issue by kelvix** [pineconellc/angular-foundation#279]
Started using mm.foundation this evening to attempt and create a few modals on top of Java / Angular services. This particular [documentation](http://pineconellc.github.io/angular-foundation/) does not appear to indicate that anything else needs to be done.

mm.foundation was added to the packages list using bower - `"angular-foundation": "~0.8.0"` details the version in use. I was able to move forward by simply copying the two files from [the repo](https://github.com/pineconellc/angular-foundation/tree/master/template/modal) and creating a template/modal/ directory on root (curious as to what will happen when my context changes in production!). 

If this is intentional and I somehow glossed over something obvious apologies in advance. If this is an issue I can try and look into things mid next week. Needless to say thank you for the awesome solution.

**Comment by jbrowning** [comment]
Please take a look at the release [bower repo](https://github.com/pineconellc/angular-foundation-bower) for an explanation of the different JS files. I believe you've included the JS file without the embedded templates.
