### ISSUE TITLE
Is there any option to specify the Modal width?

### ISSUE THREAD

**Issue by didadan** [pineconellc/angular-foundation#284]
In Reveal there are some classes to specify whether the modal opens as a small, medium or big one. Here is didn't find any documentation on this. Do you know how to size it?

Might be related to #281.

**Comment by jbrowning** [comment]
Please take a look at my comment in #281. This is already supported with the `windowClass` option for `$modal.open`.

**Comment by didadan** [comment]
Thank you, works.
