### ISSUE TITLE
Doesn't work with Tabs and foundation 6.2 Css

### ISSUE THREAD

**Issue by nicolas15000** [pineconellc/angular-foundation#295]
Hello, thanks a lot for this fantastic work.
Unfortunatly TABS are not compatible with the latest 6.2 Foundation.css.
Unable to focus any more or to get a normal CSS with angular-foundation. 

Teste with the 5.2 , it works like a charme, but the syntax is different.

I'm on a 6.2 Foundation project.

Have a nice day

**Comment by jbrowning** [comment]
Foundation 6 is not supported yet. Please follow #280 for updates.
